#!/usr/bin/env python3
"""Compile the GXM shader set to .gxp and emit gxm_shaders.h.

The header it writes is committed, so only regenerating it needs psp2cgc.

  python build_shaders.py --cgc "<path>/psp2cgc.exe"
"""

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_HEADER = os.path.join(HERE, "gxm_shaders.h")

# name -> (source, profile, [extra -D defines])
SHADERS = {
    "clear_v": ("clear_v.cg", "sce_vp_psp2", []),
    "clear_f": ("clear_f.cg", "sce_fp_psp2", []),
}

# generic set: the vertex side varies by attribute presence, the fragment side by
# texture count / env mode / alpha test. Blending is NOT a variant here -- it is
# baked into fragment-program instances at runtime by the shader patcher.
for _nuv in (0, 1, 2):
    for _vcol in (0, 1):
        for _fog in (0, 1):
            SHADERS["generic_v_u%d_c%d_f%d" % (_nuv, _vcol, _fog)] = (
                "generic_v.cg", "sce_vp_psp2",
                ["NUV=%d" % _nuv, "VCOLOR=%d" % _vcol, "FOG=%d" % _fog])

for _ntex in (0, 1, 2):
    for _env in ((0,) if _ntex < 2 else (0, 1, 2)):
        for _atest in range(5):
            for _fog in (0, 1):
                SHADERS["generic_f_t%d_e%d_a%d_f%d" % (_ntex, _env, _atest, _fog)] = (
                    "generic_f.cg", "sce_fp_psp2",
                    ["NTEX=%d" % _ntex, "ENV=%d" % _env, "ATEST=%d" % _atest, "FOG=%d" % _fog])

# match what the runtime would have asked shark for
CGC_FLAGS = ["-O3", "-fastmath", "-fastint", "-nofastprecision"]


def compile_one(cgc, name, src, profile, defines, outdir):
    out = os.path.join(outdir, name + ".gxp")
    cmd = [cgc, "-profile", profile, os.path.join(HERE, src), "-o", out] + CGC_FLAGS
    cmd += ["-D%s" % d for d in defines]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0 or not os.path.exists(out):
        sys.stderr.write("FAILED %s\n%s%s\n" % (name, r.stdout, r.stderr))
        return None
    with open(out, "rb") as f:
        blob = f.read()
    if blob[:4] != b"GXP\0":
        sys.stderr.write("FAILED %s: not a GXP blob\n" % name)
        return None
    return blob


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cgc", required=True, help="path to psp2cgc")
    ap.add_argument("--outdir", default=os.path.join(HERE, "build"))
    args = ap.parse_args()

    if not os.path.exists(args.cgc):
        sys.exit("psp2cgc not found: %s" % args.cgc)
    os.makedirs(args.outdir, exist_ok=True)

    blobs = {}
    for name, (src, profile, defines) in sorted(SHADERS.items()):
        blob = compile_one(args.cgc, name, src, profile, defines, args.outdir)
        if blob is None:
            sys.exit(1)
        blobs[name] = blob
        print("%-12s %5d bytes" % (name, len(blob)))

    lines = [
        "// Generated by build_shaders.py -- do not edit.",
        "// Compiled GXM programs; regenerate with the official psp2cgc.",
        "",
        "#ifndef GXM_SHADERS_H",
        "#define GXM_SHADERS_H",
        "",
    ]
    for name, blob in sorted(blobs.items()):
        lines.append("static const unsigned char gxs_%s[] = {" % name)
        for i in range(0, len(blob), 12):
            row = ", ".join("0x%02x" % b for b in blob[i:i + 12])
            lines.append("\t%s," % row)
        lines.append("};")
        lines.append("")
    lines.append("#endif // GXM_SHADERS_H")

    with open(OUT_HEADER, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d shaders, %d bytes total)"
          % (os.path.relpath(OUT_HEADER, HERE), len(blobs), sum(len(b) for b in blobs.values())))


if __name__ == "__main__":
    main()
