#!/usr/bin/env python3
"""Generate src/code/rd-gxm/qgl_gxm.h from the GL entry points the renderer uses.

Native GXM build: GL entry points become holes, not a translation layer. Rerun
after deleting call sites so the header shrinks as the port progresses.
"""

import io
import os
import re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QGL_H = os.path.join(HERE, "src", "code", "rd-vanilla", "qgl.h")
DST = os.path.join(HERE, "src", "code", "rd-gxm", "qgl_gxm.h")
SCAN_DIRS = ("rd-vanilla", "rd-common")

# the only qgl entry points whose return value is read anywhere
QGL_RETURNS = {
    "qglGetError": "0",
    "qglIsEnabled": "0",
    "qglGenLists": "1",
}

# gl* called directly rather than through a qgl macro, whose result is read
DIRECT_RETURNS = {
    "glGetError": "0",
    "glCheckFramebufferStatus": "0",     # incomplete: there is no offscreen target
    "glCreateProgram": "0",
    "glCreateShader": "0",
    "glGetUniformLocation": "(-1)",
}

# the immediate-mode entry points still used, mapped onto the accumulator
IMMEDIATE = {
    "qglBegin":        "(m) GXM_ImmBegin((unsigned int)(m))",
    "qglEnd":          "() GXM_ImmEnd()",
    "qglVertex2f":     "(x, y) GXM_ImmVertex3f((x), (y), 0.0f)",
    "qglVertex3f":     "(x, y, z) GXM_ImmVertex3f((x), (y), (z))",
    "qglVertex3fv":    "(v) GXM_ImmVertex3f((v)[0], (v)[1], (v)[2])",
    "qglTexCoord2f":   "(s, t) GXM_ImmTexCoord2f((s), (t))",
    "qglTexCoord2fv":  "(v) GXM_ImmTexCoord2f((v)[0], (v)[1])",
    "qglColor3f":      "(r, g, b) GXM_ImmColor4f((r), (g), (b), 1.0f)",
    "qglColor4f":      "(r, g, b, a) GXM_ImmColor4f((r), (g), (b), (a))",
    "qglColor4ubv":    "(v) GXM_ImmColor4ubv((const unsigned char *)(v))",
}

# gl_vita_ext.cpp defines these itself; macroing them would break the definitions
DEFINED_LOCALLY = {"glTexParameterfv", "glDrawBuffer", "glArrayElement"}

qgl_re = re.compile(r"#define\s+(qgl[A-Za-z0-9_]+)\s")
direct_re = re.compile(r"\b(gl[A-Z][A-Za-z0-9_]*)\s*\(")

qgl_h_text = io.open(QGL_H, encoding="latin1").read()
qgl_names = sorted(set(qgl_re.findall(qgl_h_text)))

# qgl.h also declares extension entry points as extern function pointers. Most are
# defined NULL by gl_vita_ext.cpp and their call sites are already guarded by
# `if (qgl...)`, so those stay inert on their own; only the rest need holing.
ext_re = re.compile(r"^extern\s+PFN\w+\s+(qgl\w+)\s*;", re.M)
ext_all = set(ext_re.findall(qgl_h_text))
ext_local = set(re.findall(r"(qgl[A-Za-z0-9_]+)\s*=",
                io.open(os.path.join(HERE, "src", "code", "rd-vanilla", "gl_vita_ext.cpp"),
                        encoding="latin1", errors="replace").read()))
# These are used both as calls and as bare truthiness tests (`if (qglX)`), so a
# function-like macro would vanish in the test. They map to real no-op functions.
POINTER_NOOPS = {
    "qglActiveTextureARB": ("GXM_NoOpTexUnit", "unsigned int"),
    "qglClientActiveTextureARB": ("GXM_NoOpTexUnit", "unsigned int"),
    "qglMultiTexCoord2fARB": ("GXM_NoOpMultiTexCoord2f", "unsigned int, float, float"),
    "qglStencilOpSeparate": ("GXM_NoOpStencilOpSeparate",
                             "unsigned int, unsigned int, unsigned int, unsigned int"),
}
qgl_names = sorted(set(qgl_names) | (ext_all - ext_local))
# gl_vita_ext.cpp already provides real no-op definitions for these, and some are
# passed as function pointers, so let the qgl alias resolve to them untouched
KEEP_LOCAL_ALIASES = {"qglArrayElement", "qglTexParameterfv", "qglDrawBuffer"}
qgl_names = [n for n in qgl_names if n not in POINTER_NOOPS and n not in KEEP_LOCAL_ALIASES]

direct = set()
for d in SCAN_DIRS:
    dirpath = os.path.join(HERE, "src", "code", d)
    if not os.path.isdir(dirpath):
        continue
    for fn in sorted(os.listdir(dirpath)):
        if not fn.endswith(".cpp"):   # headers carry the full GL declaration list
            continue
        txt = io.open(os.path.join(dirpath, fn), encoding="latin1", errors="replace").read()
        direct |= set(direct_re.findall(txt))
direct -= DEFINED_LOCALLY
direct = sorted(direct)

out = [
    "// Generated by tools/gen_qgl_holes.py -- do not edit.",
    "//",
    "// The GL entry points become holes, not a translation layer; each subsystem",
    "// ported to sceGxm deletes its call sites and this file shrinks with it.",
    "",
    "#ifndef QGL_GXM_H",
    "#define QGL_GXM_H",
    "",
    # the rd-gxm headers declare some of these with C linkage, so these must agree
    "#ifdef __cplusplus",
    'extern "C" {',
    "#endif",
    "const unsigned char *GXM_GlGetString( unsigned int name );",
    "void GXM_GlGetIntegerv( unsigned int pname, int *params );",
    "void GXM_GlGetFloatv( unsigned int pname, float *params );",
    "void GXM_GlClear( unsigned int mask );",
    "void GXM_SetClearColor( float r, float g, float b, float a );",
    "void GXM_SetDepthRange( float zNear, float zFar );",
    "void GXM_SetDepthBias( float factor, float units );",
    "void GXM_ImmBegin( unsigned int glMode );",
    "void GXM_ImmTexCoord2f( float s, float t );",
    "void GXM_ImmColor4f( float r, float g, float b, float a );",
    "void GXM_ImmColor4ubv( const unsigned char *c );",
    "void GXM_ImmVertex3f( float x, float y, float z );",
    "void GXM_ImmEnd( void );",
    "#ifdef __cplusplus",
    "}",
    "#endif",
    "",
]
for n in qgl_names:
    out.append("#undef %s" % n)   # qgl.h aliased it to the GL name first
    if n == "qglGetString":
        out.append("#define %s(name) GXM_GlGetString(name)" % n)
    elif n == "qglGetIntegerv":
        out.append("#define %s(p, v) GXM_GlGetIntegerv((unsigned int)(p), (v))" % n)
    elif n == "qglGetFloatv":
        out.append("#define %s(p, v) GXM_GlGetFloatv((unsigned int)(p), (v))" % n)
    # routed here rather than at each of the dozen call sites
    elif n == "qglClear":
        out.append("#define %s(mask) GXM_GlClear((unsigned int)(mask))" % n)
    elif n == "qglClearColor":
        out.append("#define %s(r, g, b, a) GXM_SetClearColor((r), (g), (b), (a))" % n)
    # routed here so a call site in a new file cannot silently become a no-op
    elif n == "qglDepthRange":
        out.append("#define %s(n, f) GXM_SetDepthRange((float)(n), (float)(f))" % n)
    elif n == "qglPolygonOffset":
        out.append("#define %s(f, u) GXM_SetDepthBias((f), (u))" % n)
    # the remaining glBegin/glVertex blocks: weather, the cinematic quad, shadows
    elif n in IMMEDIATE:
        out.append("#define %s%s" % (n, IMMEDIATE[n]))
    elif n in QGL_RETURNS:
        out.append("#define %s(...) (%s)" % (n, QGL_RETURNS[n]))
    else:
        out.append("#define %s(...) ((void)0)" % n)

out.append("")
out.append("// used as calls AND as bare pointer tests, so these need real symbols")
for fn, args in sorted(set(POINTER_NOOPS.values())):
    out.append("void %s( %s );" % (fn, args))
for _k in sorted(POINTER_NOOPS):
    out.append("#undef %s" % _k)
    out.append("#define %s %s" % (_k, POINTER_NOOPS[_k][0]))
out.append("")
out.append("// called directly, never through a qgl macro")
for n in direct:
    if n in DIRECT_RETURNS:
        out.append("#define %s(...) (%s)" % (n, DIRECT_RETURNS[n]))
    else:
        out.append("#define %s(...) ((void)0)" % n)

out += ["", "#endif // QGL_GXM_H"]

io.open(DST, "w", newline="\n").write("\n".join(out))
print("generated %d qgl + %d direct holes -> %s"
      % (len(qgl_names), len(direct), os.path.relpath(DST, HERE)))
