#!/usr/bin/env python3
"""Generate src/code/rd-gxm/qgl_gxm.h from the GL entry points the renderer uses.

Native GXM build: GL entry points become holes, not a translation layer. Rerun
after deleting call sites so the header shrinks as the port progresses.
"""

import io
import os
import re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QGL_H = os.path.join(HERE, "src", "code", "rd-vanilla", "qgl.h")
DST = os.path.join(HERE, "src", "code", "rd-gxm", "qgl_gxm.h")
SCAN_DIRS = ("rd-vanilla", "rd-common")

# the only qgl entry points whose return value is read anywhere
QGL_RETURNS = {
    "qglGetError": "0",
    "qglIsEnabled": "0",
    "qglGenLists": "1",
}

# gl*/vgl* called directly rather than through a qgl macro, whose result is read
DIRECT_RETURNS = {
    "glGetError": "0",
    "glCheckFramebufferStatus": "0x8CD5",   # GL_FRAMEBUFFER_COMPLETE
    "glCreateProgram": "0",
    "glCreateShader": "0",
    "glGetUniformLocation": "(-1)",
    "vglMemFree": "0",
    "vglMemTotal": "0",
}

# gl_vita_ext.cpp defines these itself; macroing them would break the definitions
DEFINED_LOCALLY = {"glTexParameterfv", "glDrawBuffer", "glArrayElement"}

qgl_re = re.compile(r"#define\s+(qgl[A-Za-z0-9_]+)\s")
direct_re = re.compile(r"\b((?:vgl|gl)[A-Z][A-Za-z0-9_]*)\s*\(")

qgl_h_text = io.open(QGL_H, encoding="latin1").read()
qgl_names = sorted(set(qgl_re.findall(qgl_h_text)))

# qgl.h also declares extension entry points as extern function pointers. Most are
# defined NULL by gl_vita_ext.cpp and their call sites are already guarded by
# `if (qgl...)`, so those stay inert on their own; only the ones vitaGL really
# provides need holing.
ext_re = re.compile(r"^extern\s+PFN\w+\s+(qgl\w+)\s*;", re.M)
ext_all = set(ext_re.findall(qgl_h_text))
ext_local = set(re.findall(r"(qgl[A-Za-z0-9_]+)\s*=",
                io.open(os.path.join(HERE, "src", "code", "rd-vanilla", "gl_vita_ext.cpp"),
                        encoding="latin1", errors="replace").read()))
# These are used both as calls and as bare truthiness tests (`if (qglX)`), so a
# function-like macro would vanish in the test. They map to real no-op functions.
POINTER_NOOPS = {
    "qglActiveTextureARB": ("GXM_NoOpTexUnit", "unsigned int"),
    "qglClientActiveTextureARB": ("GXM_NoOpTexUnit", "unsigned int"),
    "qglMultiTexCoord2fARB": ("GXM_NoOpMultiTexCoord2f", "unsigned int, float, float"),
    "qglStencilOpSeparate": ("GXM_NoOpStencilOpSeparate",
                             "unsigned int, unsigned int, unsigned int, unsigned int"),
}
qgl_names = sorted(set(qgl_names) | (ext_all - ext_local))
# gl_vita_ext.cpp already provides real no-op definitions for these, and some are
# passed as function pointers, so let the qgl alias resolve to them untouched
KEEP_LOCAL_ALIASES = {"qglArrayElement", "qglTexParameterfv", "qglDrawBuffer"}
qgl_names = [n for n in qgl_names if n not in POINTER_NOOPS and n not in KEEP_LOCAL_ALIASES]

direct = set()
for d in SCAN_DIRS:
    dirpath = os.path.join(HERE, "src", "code", d)
    if not os.path.isdir(dirpath):
        continue
    for fn in sorted(os.listdir(dirpath)):
        if not fn.endswith(".cpp"):   # headers carry the full GL declaration list
            continue
        txt = io.open(os.path.join(dirpath, fn), encoding="latin1", errors="replace").read()
        direct |= set(direct_re.findall(txt))
direct -= DEFINED_LOCALLY
direct = sorted(direct)

out = [
    "// Generated by tools/gen_qgl_holes.py -- do not edit.",
    "//",
    "// Native GXM build: the GL entry points become holes, not a translation layer.",
    "// Each renderer subsystem ported to sceGxm deletes its call sites, and this",
    "// file shrinks with it. Nothing here emulates GL.",
    "",
    "#ifndef QGL_GXM_H",
    "#define QGL_GXM_H",
    "",
    "const unsigned char *GXM_GlGetString( unsigned int name );",
    "",
]
for n in qgl_names:
    if n == "qglGetString":
        out.append("#define %s(name) GXM_GlGetString(name)" % n)
    elif n in QGL_RETURNS:
        out.append("#define %s(...) (%s)" % (n, QGL_RETURNS[n]))
    else:
        out.append("#define %s(...) ((void)0)" % n)

out.append("")
out.append("// used as calls AND as bare pointer tests, so these need real symbols")
for fn, args in sorted(set(POINTER_NOOPS.values())):
    out.append("void %s( %s );" % (fn, args))
for _k in sorted(POINTER_NOOPS):
    out.append("#define %s %s" % (_k, POINTER_NOOPS[_k][0]))
out.append("")
out.append("// called directly, never through a qgl macro")
for n in direct:
    if n in DIRECT_RETURNS:
        out.append("#define %s(...) (%s)" % (n, DIRECT_RETURNS[n]))
    else:
        out.append("#define %s(...) ((void)0)" % n)

out += ["", "#endif // QGL_GXM_H"]

io.open(DST, "w", newline="\n").write("\n".join(out))
print("generated %d qgl + %d direct holes -> %s"
      % (len(qgl_names), len(direct), os.path.relpath(DST, HERE)))
