#!/usr/bin/env python3
"""Generate src/code/rd-gxm/qgl_gxm.h from the qgl entry points qgl.h declares.

Native GXM build: GL entry points become holes, not a translation layer. Rerun
after deleting call sites so the header shrinks with the port.
"""

import io
import os
import re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "src", "code", "rd-vanilla", "qgl.h")
DST = os.path.join(HERE, "src", "code", "rd-gxm", "qgl_gxm.h")

# the only entry points whose return value is read anywhere in the renderer
RETURNS = {
    "qglGetError": "0",
    "qglIsEnabled": "0",
    "qglGenLists": "1",
}

names = sorted(set(re.findall(r"#define\s+(qgl[A-Za-z0-9_]+)\s",
                              io.open(SRC, encoding="latin1").read())))

out = [
    "// Generated by tools/gen_qgl_holes.py -- do not edit.",
    "//",
    "// Native GXM build: the GL entry points become holes, not a translation layer.",
    "// Each renderer subsystem ported to sceGxm deletes its call sites, and this",
    "// file shrinks with it. Nothing here emulates GL.",
    "",
    "#ifndef QGL_GXM_H",
    "#define QGL_GXM_H",
    "",
    "const unsigned char *GXM_GlGetString( unsigned int name );",
    "",
]
for n in names:
    if n == "qglGetString":
        out.append("#define %s(name) GXM_GlGetString(name)" % n)
    elif n in RETURNS:
        out.append("#define %s(...) (%s)" % (n, RETURNS[n]))
    else:
        out.append("#define %s(...) ((void)0)" % n)
out += ["", "#endif // QGL_GXM_H"]

io.open(DST, "w", newline="\n").write("\n".join(out))
print("generated %d holes (%d with return values) -> %s"
      % (len(names), len(RETURNS) + 1, os.path.relpath(DST, HERE)))
