# Shared engine half + a game half picked by BUILD_JKA:
#   OFF -> Jedi Outcast (codeJK2/, JK2_MODE)       -> JK2VITA.vpk
#   ON  -> Jedi Academy (code/{game,cgame,icarus}) -> JAVITA.vpk
# JKA list matches StaticJK's. Two gotchas: no animtable.cpp (the table lives in
# code/cgame/animtable.h), and use bg_vehicleLoad.cpp, not g_vehicleLoad.cpp.

#----------------------------------------------------------------------------
# Engine half (shared, Vita-working) — identical for JK2 and JKA.
#----------------------------------------------------------------------------
set(JK_ENGINE_SOURCES
    src/code/Ratl/ratl.cpp
    src/code/Ravl/CBounds.cpp
    src/code/Ravl/CVec.cpp
    src/code/Rufl/hfile.cpp
    src/code/Rufl/hstring.cpp
    src/code/client/cl_cgame.cpp
    src/code/client/cl_cin.cpp
    src/code/client/cl_console.cpp
    src/code/client/cl_input.cpp
    src/code/client/cl_keys.cpp
    src/code/client/cl_main.cpp
    src/code/client/cl_mp3.cpp
    src/code/client/cl_parse.cpp
    src/code/client/cl_scrn.cpp
    src/code/client/cl_ui.cpp
    src/code/client/snd_ambient.cpp
    src/code/client/snd_dma.cpp
    src/code/client/snd_mem.cpp
    src/code/client/snd_mix.cpp
    src/code/client/snd_music.cpp
    src/code/client/vmachine.cpp
    src/code/mp3code/cdct.c
    src/code/mp3code/csbt.c
    src/code/mp3code/csbtb.c
    src/code/mp3code/csbtl3.c
    src/code/mp3code/cup.c
    src/code/mp3code/cupini.c
    src/code/mp3code/cupl1.c
    src/code/mp3code/cupl3.c
    src/code/mp3code/cwin.c
    src/code/mp3code/cwinb.c
    src/code/mp3code/cwinm.c
    src/code/mp3code/hwin.c
    src/code/mp3code/l3dq.c
    src/code/mp3code/l3init.c
    src/code/mp3code/mdct.c
    src/code/mp3code/mhead.c
    src/code/mp3code/msis.c
    src/code/mp3code/towave.c
    src/code/mp3code/uph.c
    src/code/mp3code/upsf.c
    src/code/mp3code/wavep.c
    src/code/qcommon/cm_load.cpp
    src/code/qcommon/cm_patch.cpp
    src/code/qcommon/cm_polylib.cpp
    src/code/qcommon/cm_test.cpp
    src/code/qcommon/cm_trace.cpp
    src/code/qcommon/cmd.cpp
    src/code/qcommon/common.cpp
    src/code/qcommon/cvar.cpp
    src/code/qcommon/files.cpp
    src/code/qcommon/matcomp.cpp
    src/code/qcommon/md4.cpp
    src/code/qcommon/msg.cpp
    src/code/qcommon/net_chan.cpp
    src/code/qcommon/ojk_saved_game.cpp
    src/code/qcommon/persistence.cpp
    src/code/qcommon/q_shared.cpp
    src/code/qcommon/stringed_ingame.cpp
    src/code/qcommon/stringed_interface.cpp
    src/code/qcommon/strip.cpp
    src/code/qcommon/tri_coll_test.cpp
    src/code/qcommon/z_memman_pc.cpp
    src/code/rd-common/tr_font.cpp
    src/code/rd-common/tr_image_jpg.cpp
    src/code/rd-common/tr_image_load.cpp
    src/code/rd-common/tr_image_png.cpp
    src/code/rd-common/tr_image_tga.cpp
    src/code/rd-common/tr_noise.cpp
    src/code/rd-vanilla/G2_API.cpp
    src/code/rd-vanilla/G2_bolts.cpp
    src/code/rd-vanilla/G2_bones.cpp
    src/code/rd-vanilla/G2_misc.cpp
    src/code/rd-vanilla/G2_surfaces.cpp
    src/code/rd-vanilla/tr_WorldEffects.cpp
    src/code/rd-vanilla/tr_arb.cpp
    src/code/rd-vanilla/tr_backend.cpp
    src/code/rd-vanilla/tr_bsp.cpp
    src/code/rd-vanilla/tr_cmds.cpp
    src/code/rd-vanilla/tr_curve.cpp
    src/code/rd-vanilla/tr_draw.cpp
    src/code/rd-vanilla/tr_ghoul2.cpp
    src/code/rd-vanilla/tr_image.cpp
    src/code/rd-vanilla/tr_init.cpp
    src/code/rd-vanilla/tr_light.cpp
    src/code/rd-vanilla/tr_main.cpp
    src/code/rd-vanilla/tr_marks.cpp
    src/code/rd-vanilla/tr_mesh.cpp
    src/code/rd-vanilla/tr_model.cpp
    src/code/rd-vanilla/tr_quicksprite.cpp
    src/code/rd-vanilla/tr_scene.cpp
    src/code/rd-vanilla/tr_shade.cpp
    src/code/rd-vanilla/tr_shade_calc.cpp
    src/code/rd-vanilla/tr_shader.cpp
    src/code/rd-vanilla/tr_shadows.cpp
    src/code/rd-vanilla/tr_skin.cpp
    src/code/rd-vanilla/tr_sky.cpp
    src/code/rd-vanilla/tr_stl.cpp
    src/code/rd-vanilla/tr_subs.cpp
    src/code/rd-vanilla/tr_surface.cpp
    src/code/rd-vanilla/tr_surfacesprites.cpp
    src/code/rd-vanilla/tr_world.cpp
    src/code/rd-vanilla/tr_worldvbo.cpp
    src/code/server/exe_headers.cpp
    src/code/server/sv_ccmds.cpp
    src/code/server/sv_client.cpp
    src/code/server/sv_game.cpp
    src/code/server/sv_init.cpp
    src/code/server/sv_main.cpp
    src/code/server/sv_savegame.cpp
    src/code/server/sv_snapshot.cpp
    src/code/server/sv_world.cpp
    src/code/ui/gameinfo.cpp
    src/code/ui/ui_atoms.cpp
    src/code/ui/ui_connect.cpp
    src/code/ui/ui_main.cpp
    src/code/ui/ui_saber.cpp
    src/code/ui/ui_shared.cpp
    src/code/ui/ui_syscalls.cpp
    src/lib/minizip/ioapi.c
    src/lib/minizip/unzip.c
    src/shared/qcommon/q_color.c
    src/shared/qcommon/q_math.c
    src/shared/qcommon/q_string.c
    src/shared/qcommon/safe/files.cpp
    src/shared/qcommon/safe/string.cpp
    src/shared/sdl/sdl_input.cpp
    src/shared/sdl/sdl_sound.cpp
    src/shared/sdl/sdl_window.cpp
    src/shared/sys/con_log.cpp
    src/shared/sys/con_tty.cpp
    src/shared/sys/snapvector.cpp
    src/shared/sys/sys_event.cpp
    src/shared/sys/sys_main.cpp
    src/shared/sys/sys_unix.cpp
    # ---- JK2VITA Vita compat (shared) ----
    src/code/rd-vanilla/gl_vita_ext.cpp
    src/globals.cpp
)

#----------------------------------------------------------------------------
# Jedi Outcast game half — codeJK2/ (built when BUILD_JKA is OFF).
#----------------------------------------------------------------------------
set(JK2_GAME_SOURCES
    src/codeJK2/game/AI_Atst.cpp
    src/codeJK2/game/AI_Default.cpp
    src/codeJK2/game/AI_Droid.cpp
    src/codeJK2/game/AI_GalakMech.cpp
    src/codeJK2/game/AI_Grenadier.cpp
    src/codeJK2/game/AI_Howler.cpp
    src/codeJK2/game/AI_ImperialProbe.cpp
    src/codeJK2/game/AI_Interrogator.cpp
    src/codeJK2/game/AI_Jedi.cpp
    src/codeJK2/game/AI_Mark1.cpp
    src/codeJK2/game/AI_Mark2.cpp
    src/codeJK2/game/AI_MineMonster.cpp
    src/codeJK2/game/AI_Remote.cpp
    src/codeJK2/game/AI_Seeker.cpp
    src/codeJK2/game/AI_Sentry.cpp
    src/codeJK2/game/AI_Sniper.cpp
    src/codeJK2/game/AI_Stormtrooper.cpp
    src/codeJK2/game/AI_Utils.cpp
    src/codeJK2/game/G_Timer.cpp
    src/codeJK2/game/NPC.cpp
    src/codeJK2/game/NPC_behavior.cpp
    src/codeJK2/game/NPC_combat.cpp
    src/codeJK2/game/NPC_goal.cpp
    src/codeJK2/game/NPC_misc.cpp
    src/codeJK2/game/NPC_move.cpp
    src/codeJK2/game/NPC_reactions.cpp
    src/codeJK2/game/NPC_senses.cpp
    src/codeJK2/game/NPC_sounds.cpp
    src/codeJK2/game/NPC_spawn.cpp
    src/codeJK2/game/NPC_stats.cpp
    src/codeJK2/game/NPC_utils.cpp
    src/codeJK2/game/Q3_Interface.cpp
    src/codeJK2/game/Q3_Registers.cpp
    src/codeJK2/game/bg_misc.cpp
    src/codeJK2/game/bg_pangles.cpp
    src/codeJK2/game/bg_panimate.cpp
    src/codeJK2/game/bg_pmove.cpp
    src/codeJK2/game/bg_slidemove.cpp
    src/codeJK2/game/g_ICARUS.cpp
    src/codeJK2/game/g_active.cpp
    src/codeJK2/game/g_breakable.cpp
    src/codeJK2/game/g_camera.cpp
    src/codeJK2/game/g_client.cpp
    src/codeJK2/game/g_cmds.cpp
    src/codeJK2/game/g_combat.cpp
    src/codeJK2/game/g_functions.cpp
    src/codeJK2/game/g_fx.cpp
    src/codeJK2/game/g_inventory.cpp
    src/codeJK2/game/g_itemLoad.cpp
    src/codeJK2/game/g_items.cpp
    src/codeJK2/game/g_main.cpp
    src/codeJK2/game/g_mem.cpp
    src/codeJK2/game/g_misc.cpp
    src/codeJK2/game/g_misc_model.cpp
    src/codeJK2/game/g_missile.cpp
    src/codeJK2/game/g_mover.cpp
    src/codeJK2/game/g_nav.cpp
    src/codeJK2/game/g_navigator.cpp
    src/codeJK2/game/g_navnew.cpp
    src/codeJK2/game/g_object.cpp
    src/codeJK2/game/g_objectives.cpp
    src/codeJK2/game/g_ref.cpp
    src/codeJK2/game/g_roff.cpp
    src/codeJK2/game/g_savegame.cpp
    src/codeJK2/game/g_session.cpp
    src/codeJK2/game/g_spawn.cpp
    src/codeJK2/game/g_svcmds.cpp
    src/codeJK2/game/g_target.cpp
    src/codeJK2/game/g_trigger.cpp
    src/codeJK2/game/g_turret.cpp
    src/codeJK2/game/g_usable.cpp
    src/codeJK2/game/g_utils.cpp
    src/codeJK2/game/g_weapon.cpp
    src/codeJK2/game/g_weaponLoad.cpp
    src/codeJK2/game/genericparser2.cpp
    src/codeJK2/game/wp_atst.cpp
    src/codeJK2/game/wp_blaster_rifle.cpp
    src/codeJK2/game/wp_bot_laser.cpp
    src/codeJK2/game/wp_bowcaster.cpp
    src/codeJK2/game/wp_bryar_pistol.cpp
    src/codeJK2/game/wp_demp2.cpp
    src/codeJK2/game/wp_det_pack.cpp
    src/codeJK2/game/wp_disruptor.cpp
    src/codeJK2/game/wp_emplaced_gun.cpp
    src/codeJK2/game/wp_flechette.cpp
    src/codeJK2/game/wp_melee.cpp
    src/codeJK2/game/wp_repeater.cpp
    src/codeJK2/game/wp_rocket_launcher.cpp
    src/codeJK2/game/wp_saber.cpp
    src/codeJK2/game/wp_stun_baton.cpp
    src/codeJK2/game/wp_thermal.cpp
    src/codeJK2/game/wp_trip_mine.cpp
    src/codeJK2/cgame/FX_ATSTMain.cpp
    src/codeJK2/cgame/FX_Blaster.cpp
    src/codeJK2/cgame/FX_Bowcaster.cpp
    src/codeJK2/cgame/FX_BryarPistol.cpp
    src/codeJK2/cgame/FX_DEMP2.cpp
    src/codeJK2/cgame/FX_Disruptor.cpp
    src/codeJK2/cgame/FX_Emplaced.cpp
    src/codeJK2/cgame/FX_Flechette.cpp
    src/codeJK2/cgame/FX_HeavyRepeater.cpp
    src/codeJK2/cgame/FX_RocketLauncher.cpp
    src/codeJK2/cgame/FxPrimitives.cpp
    src/codeJK2/cgame/FxScheduler.cpp
    src/codeJK2/cgame/FxSystem.cpp
    src/codeJK2/cgame/FxTemplate.cpp
    src/codeJK2/cgame/FxUtil.cpp
    src/codeJK2/cgame/cg_camera.cpp
    src/codeJK2/cgame/cg_consolecmds.cpp
    src/codeJK2/cgame/cg_credits.cpp
    src/codeJK2/cgame/cg_draw.cpp
    src/codeJK2/cgame/cg_drawtools.cpp
    src/codeJK2/cgame/cg_effects.cpp
    src/codeJK2/cgame/cg_ents.cpp
    src/codeJK2/cgame/cg_event.cpp
    src/codeJK2/cgame/cg_info.cpp
    src/codeJK2/cgame/cg_lights.cpp
    src/codeJK2/cgame/cg_localents.cpp
    src/codeJK2/cgame/cg_main.cpp
    src/codeJK2/cgame/cg_marks.cpp
    src/codeJK2/cgame/cg_players.cpp
    src/codeJK2/cgame/cg_playerstate.cpp
    src/codeJK2/cgame/cg_predict.cpp
    src/codeJK2/cgame/cg_scoreboard.cpp
    src/codeJK2/cgame/cg_servercmds.cpp
    src/codeJK2/cgame/cg_snapshot.cpp
    src/codeJK2/cgame/cg_syscalls.cpp
    src/codeJK2/cgame/cg_text.cpp
    src/codeJK2/cgame/cg_view.cpp
    src/codeJK2/cgame/cg_weapons.cpp
    src/codeJK2/icarus/BlockStream.cpp
    src/codeJK2/icarus/Sequence.cpp
    src/codeJK2/icarus/Sequencer.cpp
    src/codeJK2/icarus/TaskManager.cpp
    src/codeJK2/icarus/Instance.cpp
)

#----------------------------------------------------------------------------
# Jedi Academy game half — code/{game,cgame,icarus} (stock OpenJK JKA SP,
# built when BUILD_JKA is ON). Mirrors third_party/StaticJK/CMakeLists.txt.
#----------------------------------------------------------------------------
set(JKA_GAME_SOURCES
    src/code/cgame/FX_ATSTMain.cpp
    src/code/cgame/FX_Blaster.cpp
    src/code/cgame/FX_Bowcaster.cpp
    src/code/cgame/FX_BryarPistol.cpp
    src/code/cgame/FX_Concussion.cpp
    src/code/cgame/FX_DEMP2.cpp
    src/code/cgame/FX_Disruptor.cpp
    src/code/cgame/FX_Emplaced.cpp
    src/code/cgame/FX_Flechette.cpp
    src/code/cgame/FX_HeavyRepeater.cpp
    src/code/cgame/FX_NoghriShot.cpp
    src/code/cgame/FX_RocketLauncher.cpp
    src/code/cgame/FX_TuskenShot.cpp
    src/code/cgame/FxPrimitives.cpp
    src/code/cgame/FxScheduler.cpp
    src/code/cgame/FxSystem.cpp
    src/code/cgame/FxTemplate.cpp
    src/code/cgame/FxUtil.cpp
    src/code/cgame/cg_camera.cpp
    src/code/cgame/cg_consolecmds.cpp
    src/code/cgame/cg_credits.cpp
    src/code/cgame/cg_draw.cpp
    src/code/cgame/cg_drawtools.cpp
    src/code/cgame/cg_effects.cpp
    src/code/cgame/cg_ents.cpp
    src/code/cgame/cg_event.cpp
    src/code/cgame/cg_headers.cpp
    src/code/cgame/cg_info.cpp
    src/code/cgame/cg_lights.cpp
    src/code/cgame/cg_localents.cpp
    src/code/cgame/cg_main.cpp
    src/code/cgame/cg_marks.cpp
    src/code/cgame/cg_players.cpp
    src/code/cgame/cg_playerstate.cpp
    src/code/cgame/cg_predict.cpp
    src/code/cgame/cg_scoreboard.cpp
    src/code/cgame/cg_servercmds.cpp
    src/code/cgame/cg_snapshot.cpp
    src/code/cgame/cg_syscalls.cpp
    src/code/cgame/cg_text.cpp
    src/code/cgame/cg_view.cpp
    src/code/cgame/cg_weapons.cpp
    src/code/game/AI_Animal.cpp
    src/code/game/AI_AssassinDroid.cpp
    src/code/game/AI_Atst.cpp
    src/code/game/AI_BobaFett.cpp
    src/code/game/AI_Civilian.cpp
    src/code/game/AI_Default.cpp
    src/code/game/AI_Droid.cpp
    src/code/game/AI_GalakMech.cpp
    src/code/game/AI_Grenadier.cpp
    src/code/game/AI_HazardTrooper.cpp
    src/code/game/AI_Howler.cpp
    src/code/game/AI_ImperialProbe.cpp
    src/code/game/AI_Interrogator.cpp
    src/code/game/AI_Jedi.cpp
    src/code/game/AI_Mark1.cpp
    src/code/game/AI_Mark2.cpp
    src/code/game/AI_MineMonster.cpp
    src/code/game/AI_Rancor.cpp
    src/code/game/AI_Remote.cpp
    src/code/game/AI_RocketTrooper.cpp
    src/code/game/AI_SaberDroid.cpp
    src/code/game/AI_SandCreature.cpp
    src/code/game/AI_Seeker.cpp
    src/code/game/AI_Sentry.cpp
    src/code/game/AI_Sniper.cpp
    src/code/game/AI_Stormtrooper.cpp
    src/code/game/AI_Tusken.cpp
    src/code/game/AI_Utils.cpp
    src/code/game/AI_Wampa.cpp
    src/code/game/AnimalNPC.cpp
    src/code/game/FighterNPC.cpp
    src/code/game/G_Timer.cpp
    src/code/game/NPC.cpp
    src/code/game/NPC_behavior.cpp
    src/code/game/NPC_combat.cpp
    src/code/game/NPC_goal.cpp
    src/code/game/NPC_misc.cpp
    src/code/game/NPC_move.cpp
    src/code/game/NPC_reactions.cpp
    src/code/game/NPC_senses.cpp
    src/code/game/NPC_sounds.cpp
    src/code/game/NPC_spawn.cpp
    src/code/game/NPC_stats.cpp
    src/code/game/NPC_utils.cpp
    src/code/game/Q3_Interface.cpp
    src/code/game/SpeederNPC.cpp
    src/code/game/WalkerNPC.cpp
    src/code/game/bg_misc.cpp
    src/code/game/bg_pangles.cpp
    src/code/game/bg_panimate.cpp
    src/code/game/bg_pmove.cpp
    src/code/game/bg_slidemove.cpp
    src/code/game/bg_vehicleLoad.cpp
    src/code/game/g_active.cpp
    src/code/game/g_breakable.cpp
    src/code/game/g_camera.cpp
    src/code/game/g_client.cpp
    src/code/game/g_cmds.cpp
    src/code/game/g_combat.cpp
    src/code/game/g_emplaced.cpp
    src/code/game/g_functions.cpp
    src/code/game/g_fx.cpp
    src/code/game/g_inventory.cpp
    src/code/game/g_itemLoad.cpp
    src/code/game/g_items.cpp
    src/code/game/g_main.cpp
    src/code/game/g_mem.cpp
    src/code/game/g_misc.cpp
    src/code/game/g_misc_model.cpp
    src/code/game/g_missile.cpp
    src/code/game/g_mover.cpp
    src/code/game/g_nav.cpp
    src/code/game/g_navigator.cpp
    src/code/game/g_navnew.cpp
    src/code/game/g_object.cpp
    src/code/game/g_objectives.cpp
    src/code/game/g_rail.cpp
    src/code/game/g_ref.cpp
    src/code/game/g_roff.cpp
    src/code/game/g_savegame.cpp
    src/code/game/g_session.cpp
    src/code/game/g_spawn.cpp
    src/code/game/g_svcmds.cpp
    src/code/game/g_target.cpp
    src/code/game/g_trigger.cpp
    src/code/game/g_turret.cpp
    src/code/game/g_usable.cpp
    src/code/game/g_utils.cpp
    src/code/game/g_vehicles.cpp
    src/code/game/g_weapon.cpp
    src/code/game/g_weaponLoad.cpp
    src/code/game/genericparser2.cpp
    src/code/game/wp_atst.cpp
    src/code/game/wp_blaster_pistol.cpp
    src/code/game/wp_blaster_rifle.cpp
    src/code/game/wp_bot_laser.cpp
    src/code/game/wp_bowcaster.cpp
    src/code/game/wp_concussion.cpp
    src/code/game/wp_demp2.cpp
    src/code/game/wp_det_pack.cpp
    src/code/game/wp_disruptor.cpp
    src/code/game/wp_emplaced_gun.cpp
    src/code/game/wp_flechette.cpp
    src/code/game/wp_melee.cpp
    src/code/game/wp_noghri_stick.cpp
    src/code/game/wp_repeater.cpp
    src/code/game/wp_rocket_launcher.cpp
    src/code/game/wp_saber.cpp
    src/code/game/wp_saberLoad.cpp
    src/code/game/wp_stun_baton.cpp
    src/code/game/wp_thermal.cpp
    src/code/game/wp_trip_mine.cpp
    src/code/game/wp_tusken.cpp
    src/code/icarus/BlockStream.cpp
    src/code/icarus/IcarusImplementation.cpp
    src/code/icarus/Sequence.cpp
    src/code/icarus/Sequencer.cpp
    src/code/icarus/TaskManager.cpp
)

#----------------------------------------------------------------------------
# Final source set selected by game mode.
#----------------------------------------------------------------------------
if(BUILD_JKA)
    set(JK2_SOURCES ${JK_ENGINE_SOURCES} ${JKA_GAME_SOURCES})
else()
    set(JK2_SOURCES ${JK_ENGINE_SOURCES} ${JK2_GAME_SOURCES})
endif()
